on: [push, pull_request]
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Gosec (root)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal -exclude-dir=redis -exclude-dir=badger -exclude-dir=mysql -exclude-dir=sqlite3 -exclude-dir=mongodb -exclude-dir=postgres -exclude-dir=memcache -exclude-dir=dynamodb -exclude-dir=arangodb -exclude-dir=memory ./...
        # -----
      - run: cd ./arangodb
      - name: Run Gosec (arangodb)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../badger
      - name: Run Gosec (badger)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../dynamodb
      - name: Run Gosec (dynamodb)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../memcache
      - name: Run Gosec (memcache)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../memory
      - name: Run Gosec (memory)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../mongodb
      - name: Run Gosec (mongodb)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../mysql
      - name: Run Gosec (mysql)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../postgres
      - name: Run Gosec (postgres)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../redis
      - name: Run Gosec (redis)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
        # -----
      - run: cd ../sqlite3
      - name: Run Gosec (sqlite3)
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal ./...
