on: [ push, pull_request ]
name: Security
jobs:
    Gosec:
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v2
            -   name: Install Go
                uses: actions/setup-go@v2
            -   name: Install Gosec
                run: |
                    export PATH=${PATH}:`go env GOPATH`/bin
                    go get -u github.com/securego/gosec/v2/cmd/gosec

            -   name: Run Gosec (root)
                working-directory: .
                run: gosec -exclude-dir=internal -exclude-dir=redis -exclude-dir=badger -exclude-dir=mysql -exclude-dir=sqlite3 -exclude-dir=mongodb -exclude-dir=postgres -exclude-dir=memcache -exclude-dir=dynamodb -exclude-dir=arangodb -exclude-dir=memory ./...
                # -----
            -   name: Run Gosec (arangodb)
                working-directory: ./arangodb
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (badger)
                working-directory: ./badger
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (dynamodb)
                working-directory: ./dynamodb
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (memcache)
                working-directory: ./memcache
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (memory)
                working-directory: ./memory
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (mongodb)
                working-directory: ./mongodb
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (mysql)
                working-directory: ./mysql
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (postgres)
                working-directory: ./postgres
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (redis)
                working-directory: ./redis
                run: gosec -exclude-dir=internal ./...
                # -----
            -   name: Run Gosec (sqlite3)
                working-directory: ./sqlite3
                run: gosec -exclude-dir=internal ./...
                # -----
